version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "443:443" 
      - "80:80" 
    restart: always

  api:
    depends_on:
      - nginx 
    build:
      context: .
      dockerfile: app/Dockerfile
   
    restart: always
