version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    networks:
      - network1
    ports:
      - 27017:27017
  redis:
    container_name: redis
    image: redis
    networks:
      - network1
    ports:
      - 6379:6379

  express:
    container_name: express
    build: ./express
    depends_on:
      - "redis" 
      - "mongo"
    ports:
      - 3000:3000
    networks:
      - network1
    command: ["npm", "start"]


networks:
    network1:
        external: false
        name: network1