version: '3'

services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
      MYSQL_ROOT_PASSWORD: my_root_password
    networks:
      - my_network

  web:
    image: nginx
    ports:
      - "80:80"
    networks:
      - my_network
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./log:/var/log/nginx 

networks:
  my_network:
