version: "3.9"
services:
  db:
    container_name: db
    image: mongo:4.1.13
    networks:
      - net_A
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27019:27017"

  
networks:
  net_A:

volumes:
  mongodb_data:
